// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibaonnnakuuerrgtilze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliYW9ubm5ha3V1ZXJyZ3RpbHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzgxNTksImV4cCI6MjA2OTExNDE1OX0.16un-vvPxeIvC7kQyokpfZ6nt3adRM7HyMw9hyrMagE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});